### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by joshmoore** [joshmoore/ome-ld#1]
## v0.1

The first goal of this repository is to provide a landing page for anyone wanting to use LD/RDF representations of the OME Model.

 * Code
   * Convert OME-XSD to LinkML (using ome-types)
   * Define omero-marshal URIs in LinkML
   * Review URIs between omero-marshal (v1), omero-rdf (v2), and ld.o.org
   * Convert XML to RDF
   * Convert RDF to XML
   * Write unit tests to show that conversion is lossless
 * Landing page ("ome.github.io/ld")
    - [ ] publish to ld.openmicroscopy.org
    - [ ] Decide if this is under an overarching standards org and how it relates to: NGFF, NGM, "BioImageLD (BILD)", GIDE, micRO-Crate, FAIR-IO (if at all)?
    - [ ] Include JSON-LD and Sparql playgrounds if possible
    - [ ] Provide some in-browser visualization, even when pointing to an OMERO?
    - [ ] Include information on specs like linkml and fairsignposting
    - [ ] Clearly explain the current OME(RO) RDF variants and converting between them
    - [ ] Define the future goals both for OMERO and IDR
    - [ ] Define Use cases features benefits etc.
    - [ ] Provide basics for learning about linked data (from existing books?)
    - [ ] Include IDR linkml and examples
    - [ ] Explain how to slurp into endpoint
    - [ ] Provide an example (or working buttons?) for sending to wikidata, etc.
    - [ ] How to convert OTHER xsds that use ld o org (LOO!)
    - [ ] List Funding on a page
    - [ ] Linked ome? Linked bioimaging?
    - [ ] Demo extension (in XSD?)

## Next steps
 * Evaluate an extension of this base model
 * Create XSD for OMERO extensions beyond OME-XSD
 * Support these XSD in ome-types
 * Convert these XSD to LinkML
 * Make default ome-types JSON into LD with @context
 * Applications
   - integrate in omero-marshal
   - integrate in omero-transfer
   - integrate in omero-rdf
